#!/usr/bin/env bash
# Sync Google Sign-In iOS client IDs from apps/mobile/.env → ios/Flutter/GoogleSignIn.xcconfig
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/apps/mobile/.env"
OUT="$ROOT/apps/mobile/ios/Flutter/GoogleSignIn.xcconfig"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing $ENV_FILE" >&2
  exit 1
fi

read_env() {
  local key="$1"
  local line
  # Missing keys must not fail under `set -e` / pipefail.
  line="$(grep -E "^${key}=" "$ENV_FILE" | head -1 || true)"
  if [[ -z "$line" ]]; then
    printf ''
    return 0
  fi
  printf '%s' "${line#*=}" | tr -d '"' | tr -d "'" | tr -d '\r'
}

SERVER_ID="$(read_env GOOGLE_SERVER_CLIENT_ID)"
IOS_ID="$(read_env GOOGLE_IOS_CLIENT_ID)"
URL_SCHEME=""

if [[ -n "$IOS_ID" ]]; then
  # 123-abc.apps.googleusercontent.com → com.googleusercontent.apps.123-abc
  URL_SCHEME="com.googleusercontent.apps.${IOS_ID%.apps.googleusercontent.com}"
fi

cat > "$OUT" <<EOF
// Auto-generated by scripts/sync-ios-google-signin.sh — do not edit by hand.
GOOGLE_IOS_CLIENT_ID=$IOS_ID
GOOGLE_SERVER_CLIENT_ID=$SERVER_ID
GOOGLE_IOS_URL_SCHEME=$URL_SCHEME
EOF

echo "Wrote $OUT"
if [[ -z "$IOS_ID" ]]; then
  echo "WARNING: GOOGLE_IOS_CLIENT_ID is empty — Google Sign-In on iOS will not work until you add an iOS OAuth client for bundle tv.onesign.onesignConsole."
else
  echo "iOS Google Sign-In URL scheme: $URL_SCHEME"
fi
